Liberdoc/Models/Document.cs
using System;

namespace Liberdoc.Models
{
    public class Document
    {
        public virtual Guid Id { get; set; }
        public virtual string FileName { get; set; }
        public virtual string RealName { get; set; }
        public virtual string Path { get; set; }
        public virtual Person Author { get; set; }
        public virtual DateTime Date { get; set; }
        public virtual byte[] Bytes { get; set; }
    }
}

Liberdoc/Controllers/DocumentsController.cs
using Liberdoc.Models;
using Liberdoc.Models.Minor;
using Liberdoc.Models.Repositoies;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Liberdoc.Controllers
{
    [Authorize]
    public class DocumentsController : Controller
    {
        public ActionResult Index()
        {
            var documentRepository = new DocumentRepository();
            ViewBag.Documents = documentRepository.GetOrderedBy("FileName");
            return View();
        }

        public ActionResult Upload()
        {
            return RedirectToAction("Index");
        }

        [HttpGet]
        public FileResult Download(string file_id)
        {
            var documentRepository = new DocumentRepository();
            var document = documentRepository.GetByStringGuid(file_id);
            if (document != null)
            {
                if (!System.IO.File.Exists(document.Path + document.Id.ToString()))
                {
                    System.IO.File.WriteAllBytes(document.Path + document.Id.ToString(), document.Bytes);
                }
                return File(document.Path + document.Id.ToString(), "application/octet-stream", document.RealName);
            }
            return null;
        }

        [HttpPost]
        public ActionResult UploadResult(DocumentUpload model, HttpPostedFileBase upload)
        {
            var result = new DocumentUploadResult();
            if (upload != null)
            {
                string fileName = Path.GetFileName(upload.FileName);
                if (!Directory.Exists(Server.MapPath("~/Files/")))
                {
                    Directory.CreateDirectory(Server.MapPath("~/Files/"));
                }
                if (ModelState.IsValid)
                {
                    var personRepository = new PersonRepository();
                    Person person = personRepository.GetByStringGuid(User.Identity.Name.ToString());
                    Document document = new Document()
                    {
                        Id = new Guid(),
                        FileName = model.Name,
                        RealName = fileName,
                        Path = Server.MapPath("~/Files/"),
                        Date = DateTime.Now,
                        Author = person,
                        Bytes = new byte[upload.InputStream.Length]
                    };
                    upload.InputStream.Read(document.Bytes, 0, (int)upload.InputStream.Length);
                    upload.SaveAs(Server.MapPath($"~/Files/{document.Id.ToString()}"));

                    var documentRepositiry = new DocumentRepository();
                    documentRepositiry.Add(document);

                    result.Result = $"Файл {fileName} успешно загружен под именем \"{model.Name}\"";
                }
                else
                {
                    result.Result = "Что-то пошло не так, мы уже разбираемся";
                }
            }
            else
            {
                result.Result = "Не был выбран файл!";
            }
            return View(result);
        }

        public ActionResult Find()
        {
            return RedirectToAction("Index");
        }

        public ActionResult Order(string orderby)
        {
            var documentRepository = new DocumentRepository();
            var documents = documentRepository.GetOrderedBy(orderby);
            
            return PartialView(documents);
        }
    }
}

Liberdoc/Views/Documents/Find.cshtml
<div id="findresults">
    @Html.Partial("Order")
</div>

Liberdoc/Views/Documents/Index.cshtml
@{
    ViewBag.Title = "Документы";
}

<div class="jumbotron">
    <h1>Документы</h1>
    @Html.Partial("Upload")
    @Html.Partial("Find")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Liberdoc/Views/Documents/Order.cshtml
@model IEnumerable<Liberdoc.Models.Document>
<table class="table table-condensed table-hover">
    <thead>
        <tr>
            <th>
                @Ajax.ActionLink("Имя", "Order", new { orderby = "FileName" }, new AjaxOptions { UpdateTargetId = "findresults" })
            </th>
            <th>
                @Ajax.ActionLink("Файл", "Order", new { orderby = "RealName" }, new AjaxOptions { UpdateTargetId = "findresults" })
            </th>
            <th>
                @Ajax.ActionLink("Дата создания", "Order", new { orderby = "Date" }, new AjaxOptions { UpdateTargetId = "findresults" })
            </th>
            <th>
                @Ajax.ActionLink("Автор", "Order", new { orderby = "Author" }, new AjaxOptions { UpdateTargetId = "findresults" })
            </th>
            <th>Скачать</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in Model ?? ViewBag.Documents)
            {
                <tr>
                    @{
                        string name = $"{(item.FileName.Length > 30 ? $"{item.FileName.Substring(0, 30)}..." : item.FileName)}",
                        realname = $"{(item.RealName.Length > 30 ? $"{item.RealName.Substring(0, 30)}..." : item.RealName)}",
                        date = item.Date.ToString(),
                        author = item.Author.Username;
                    }
                    <td>@name</td>
                    <td>@realname</td>
                    <td>@date</td>
                    <td>@author</td>
                    <td>
                        <a href="@Url.Action("Download", "Documents", new { file_id = item.Id.ToString() })">
                            <img src="~/images/ico_download.png" alt="" />
                        </a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

Liberdoc/Views/Documents/Upload.cshtml
@model Liberdoc.Models.Minor.DocumentUpload

@using (Html.BeginForm("UploadResult", "Documents", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <p class="lead">
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.Name, new { @class = "" })
                <div class="form-horizontal">
                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Файл документа")
                <div class="form-horizontal">
                    <input id="upload" name="upload" type="file" class="btn btn-default" data-val="true" data-val-required="File is required" />
                </div>
            </div>
            <div class="form-group">
                <div class="form-horizontal">
                    <input type="submit" value="Отправить" class="btn btn-default" />
                </div>
            </div>
        </div>
    </p>
}

Liberdoc/Views/Documents/UploadResult.cshtml
@model Liberdoc.Models.Minor.DocumentUploadResult

<p><h2>@Model.Result</h2></p>
<p>@Html.ActionLink("Вернуться", "Index", "Documents", new { area = "" }, new { @class = "btn btn-primary btn-lg" })</p>